services:
    Google_Client:
        class: Google_Client
        calls:
            - [setDeveloperKey, ['%env(GOOGLE_API_KEY)%']]
            - [setClientId, ['%env(GOOGLE_OAUTH_CLIENT_ID)%']]
            - [setClientSecret, ['%env(GOOGLE_OAUTH_CLIENT_SECRET)%']]
