framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: default

            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: failed
                retry_strategy:
                    max_retries: 5
                    delay: 5000
                    multiplier: 3


            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\Playlist\PullPlaylistVideos': async
            'App\Message\Slack\NewSlackConversation': async
            'App\Message\Slack\NewSlackTeam': async
            'App\Message\Slack\NewSlackUser': async
