version: "3.9"
services:

    mariadb:
        image: mariadb:10.6.5
        container_name: youtube-playlist-mariadb
        working_dir: /application
        networks:
            - backend
        volumes:
            - /var/lib/mysql/data:/var/lib/mysql
            - /var/lib/mysql/logs:/var/log/mysqld.log
            - /var/docker/mariadb/conf:/etc/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=database
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        ports:
            - "3003:3306"

    web:
        image: nginx:alpine
        container_name: youtube-playlist-web
        working_dir: /application
        networks:
            - frontend
            - backend
        volumes:
            - code:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

    php:
        build: docker/php-fpm
        container_name: youtube-playlist-php
        working_dir: /application
        networks:
            - frontend
            - backend
        volumes:
            - code:/application
        expose:
            - "9000"

    node:
        image: node:12.22.1
        container_name: youtube-playlist-node
        working_dir: /application
        networks:
            - frontend
        volumes:
            - code:/application

    ngrok:
        image: wernight/ngrok
        container_name: youtube-playlist-ngrok
        ports:
            - "4040:4040"
        command: ["ngrok", "http", "web:80"]

#    rabbitmq:
#        image: rabbitmq:3.8-management
#        container_name: youtube-playlist-rabbitmq
#        environment:
#            RABBITMQ_DEFAULT_USER: user
#            RABBITMQ_DEFAULT_PASS: XGkN4W33DNtsjWYn
#            RABBITMQ_DEFAULT_VHOST: mqdev
#        ports: [5672, 15672]
#        restart: always

#    redis:
#        image: redis:5-alpine
#        container_name: youtube-playlist-redis
#        ports: [6379]

networks:
    frontend:
    backend:

volumes:
    code:
        driver: local
        driver_opts:
            type: none
            device: $PWD
            o: bind

x-mutagen:
    sync:
        defaults:
            ignore:
                vcs: true
        code:
            alpha: "."
            beta: "volume://code"
            mode: "two-way-resolved"
