version: "3.1"
services:

    mariadb:
        image: mariadb:10.5
        container_name: youtube-playlist-mariadb
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=database
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        ports:
            - "3003:3306"

    web:
        image: nginx:alpine
        container_name: youtube-playlist-web
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

    php:
        image: php:7-fpm
        build: docker/php-fpm
        container_name: youtube-playlist-php
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    node:
        image: node:12.22.1
        container_name: youtube-playlist-node
        working_dir: /application
        volumes:
            - .:/application

    ngrok:
        image: wernight/ngrok
        container_name: youtube-playlist-ngrok
        ports:
            - "4040:4040"
        command: ["ngrok", "http", "web:80"]

#    rabbitmq:
#        image: rabbitmq:3.8-management
#        container_name: youtube-playlist-rabbitmq
#        environment:
#            RABBITMQ_DEFAULT_USER: user
#            RABBITMQ_DEFAULT_PASS: XGkN4W33DNtsjWYn
#            RABBITMQ_DEFAULT_VHOST: mqdev
#        ports: [5672, 15672]
#        restart: always
#
#    redis:
#        image: redis:5-alpine
#        container_name: youtube-playlist-redis
#        ports: [6379]
