version: "3.4"
services:

    mariadb:
        image: mariadb:10.6.5
        container_name: '${APP_NAME}-mariadb'
        restart: on-failure
        volumes:
            - ${PWD}/mariadb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=example
            - MYSQL_DATABASE=database
            - MYSQL_USER=root
        ports:
            - "3003:3306"

    web:
        image: nginx:1.19.10
        container_name: '${APP_NAME}-web'
        working_dir: /application
        depends_on:
            - php
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

    php:
        build: docker/php-fpm
        container_name: '${APP_NAME}-php'
        working_dir: /application
        volumes:
            - .:/application

    node:
        image: node:12.22.1
        container_name: '${APP_NAME}-node'
        working_dir: /application
        volumes:
            - .:/application

    ngrok:
        image: wernight/ngrok
        container_name: '${APP_NAME}-ngrok'
        ports:
            - "4040:4040"
        command: ["ngrok", "http", "web:80"]

#    rabbitmq:
#        image: rabbitmq:3.8-management
#        container_name: youtube-playlist-rabbitmq
#        environment:
#            RABBITMQ_DEFAULT_USER: user
#            RABBITMQ_DEFAULT_PASS: XGkN4W33DNtsjWYn
#            RABBITMQ_DEFAULT_VHOST: mqdev
#        ports: [5672, 15672]
#        restart: always

#    redis:
#        image: redis:5-alpine
#        container_name: youtube-playlist-redis
#        ports: [6379]

    adminer:
        image: adminer
        container_name: '${APP_NAME}-adminer'
        restart: always
        ports:
            - 8081:8080

x-mutagen:
    sync:
        defaults:
            ignore:
                vcs: true
        code:
            alpha: "."
            beta: "volume://code"
            mode: "two-way-resolved"
