monolog:
    # channel logger: LoggerInterface $infoLogger
    channels: [ "info" ]
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
            channels: [ "!event" ]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: [ "!event", "!doctrine", "!console" ]
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        error_log:
            type: stream
            path: "%kernel.logs_dir%/error.log"
            level: error
        slack:
            type: slack
            channels: info
            token: '%env(SLACK_TOKEN)%'
            channel: 'U01DDGBHA5U'
            level: info
            timeout: 1
            use_short_attachment: true
        slackwebhook:
            type: slackwebhook
            webhook_url: '%env(SLACK_ERROR_WEBHOOK_URL)%'
            channel: '#youtube-playlist-error-log'
            level: error
            use_short_attachment: true

# https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Configuration.php
