name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Builde docker-compose
      run: docker-compose up -d

    - name: Validate composer.json and composer.lock
      run: docker-compose run php composer validate --strict

    - name: Install dependencies
      run: docker-compose run php composer install --prefer-dist --no-progress

    - name: Run test suite
      run: docker-compose run php composer run-script test

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v2
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-php-
